import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";//clerkishlashi uchun loyihani asosiy jsx faili shu proviserga o'ralishi kerak
import { ThemeProvider } from "@/components/providers/theme-provider";

//bu shu loyihani eng asosiy root yani ildiz papkasi yani loyiha ishlashi uchun asosiy providerlar ishlatiladigan joy// layout.tsx next jsda asosiy fail hissoblanadi yani app padhodda 

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ClerkProvider>
            {/* clerk ishlashi uchun asosiy layout papkasi clerkprovider kutubhonasiga o'rab olinishi kerak shunda clerk butun loyihani o'rab olgan hissoblanadi aks holda ishlamaydi */}
            <html lang="en" suppressHydrationWarning>
                <body className={inter.className}>
                    <ThemeProvider
                        attribute="class"
                        defaultTheme="system"
                        enableSystem
                        disableTransitionOnChange
                        storageKey="google-drive"
                    >
                        {children}
                    </ThemeProvider>
                </body>
            </html>
        </ClerkProvider>
    );
}
